In [342]:
class DataCleaning:
    def __init__(self, data):
        self.data = data
        self.column_mapping = {
            'Booking_Number': 'bookingNumber',
            #'Booking_Number': 'bookingNumber',
            #'Booking_ID': 'bookingNumber',
            'Booking_Date': 'bookingDate',
            #'Case_No': 'caseNumber',
            #'Case_Number':'caseNumber',
            #'Docket_Number': 'caseNumber',
            #'File_Number': 'caseNumber',
            #'Inmate_Number': 'inmateNumber',
            'Inmate_ID': 'imateNumber',
            #'Secondary_ID': 'inmateNumber',
            #'CID': 'inmateNumber',
            #'PID': 'inmateNumber',
            #'Housing_Location': 'housing1',
            'meta.Facility_Name':'housing1',
            #'Location': 'housing1',
            #'Facility': 'housing1',
            #'Housing_Location_Code': 'housing1a',
            #'Facility Code': 'housing1a',
            'Cell_Block': 'housing3',
            'Floor': 'housing3',
            #'Cell': 'housing3',
            'Name': 'nameFull',
            'Last_Name': 'nameLast',
            'First_Name': 'nameFirst',
            'Middle_Name': 'nameMiddle',
            'Age_Standardized': 'age',
            'DOB': 'dob',
            #'Sex': 'sex',
            #'Gender': 'sex',
            'Sex_Gender_Standardized': 'sex',
            #'Race': 'race',
            'Race_Ethnicity_Standardized':'race',
            'Eye_Color': 'eyeColor',
            #'Eyes': 'eyeColor',
            'Hair_Color': 'hairColor',
            #'Hair': 'hairColor',
            'Height': 'height',
            'Weight': 'weight',
            #'Bond Total': 'bond',
            #'Bond_Amount': 'bond',
            'Bond_Standardized.value': 'bond',
            #'Total_Bond_Amount': 'bond',
            'Total_Bail_Amount': 'bail',
            #'Bail_Amount': 'bail',
            #'First Appearance Date': 'firstappearance',
            'meta.first_seen':'firstappearance',
            'meta.last_seen':'date',
            #'Top Charge': 'topcharge',
            'Top_Charge': 'topcharge',
            #'Date': 'date',
            'meta.County': 'county'
        }
        self.columns_to_keep = [
            'nameFull',
            'bookingNumber',
            'bookingDate',
            'caseNumber',
            'inmateNumber',
            'housing1',
            'housing1a',
            'housing2',
            'housing3',
            'nameLast',
            'nameFirst',
            'nameMiddle',
            'age',
            'dob',
            'sex',
            'race',
            'eyeColor',
            'hairColor',
            'height',
            'weight',
            'bond',
            'bail',
            'topcharge',
            'firstappearance',
            'county', 
            'date'
        ]
        self.gender_mapping = {
                'M': 1,
                'm':1,
                'male':1,
                'female':0,
                'F': 0,
                'f':0,
                'Male': 1,
                'Female': 0,
                'Trans':9,
                'n': 9,
                'X': 9,
                'b': 9,
                't': 9,
                'u':9,
                'Unknown': 9,
                'transgender':9,
                'hermaphrodite':9,
                'unknown':9,
                'Unknown Gender':9,
                'Nonbinary':9
                
            }

        self.race_mapping = { 
                'W': 5,
                'w':5,
                'Wh': 5,
                'White': 5,
                'white':5,
                'B': 2,
                'b':2,
                'Bl': 2,
                'Black': 2,
                'black':2,
                'Black / African American': 2,
                'black / african american':2,
                'Black Or African American': 2,
                'A': 1,
                'AAPI':1,
                'a':1,
                'C':1,
                'c':1,
                'F':1,
                'f':1,
                'P':1,
                'p':1,
                'Fi':1,
                'As': 1, 
                'Asian': 1,
                'asian':1,
                'Asian Indian': 1,
                'Chinese': 1,
                'Ch':1,
                'J': 1,
                'j':1,
                'L':1, #L might be Laos
                'l':1,
                'K': 1, #K might be Korean
                'Korean': 1,
                'Japanese': 1,
                'vietnamese':1,
                'korean':1,
                'laotian':1,
                'Vietnamese': 1,
                'japanese':1,
                'v':1,
                'k':1,
                'Other Asian!': 1,
                'Other Asian': 1,
                'other asian':1,
                'Filipino': 1,
                'cambodian':1,
                'filipino':1,
                'chinese':1,
                'asian indian':1,
                'arabian':1,
                'middle eastern':1,
                'Asian Or Pacific Islander': 1,
                'asian or pacific islander':1,
                'asian/pacific islander':1,
                'Pacific Islander':1,
                'pacific islander':1,
                'Hawaiin/samoan':1,
                'hawaiian / pacific islander':1,
                'hawaiian':1,
                'Native Hawaiian': 1,
                'native hawaiian':1,
                'Native Hawaiian Or Other Pacific Islander': 1,
                'American Indian/alaskan Native': 1,
                'american indian/alaskan native': 1,
                'American Indian Or Alaska Native': 1,
                'Guamanian': 1,
                'guamanian':1,
                'Hawaiian': 1,
                'Samoan': 1,
                'samoan':1,
                'Pacific Islander': 1,
                'Sa': 1, #not sure if Sa = Samoa
                'V':1,
                'Asian Indian':1,
                'H': 3,
                'h':3,
                'Hi': 3,
                'Hispanic': 3,
                'hispanic':3,
                'Hispanic/latin/mexican': 3,
                'hispanic/latin/mexican':3,
                'Mexican-latin American': 3,
                'M':3, #M = Mexican
                'I': 4,
                'i':4,
                'Am': 4,
                'American Indian': 4,
                'Indigenous':4,
                'american indian':4,
                'American Indian Or Alaskan Native':4,
                'american indian or alaskan native':4,
                'Native American': 4,
                'native american':4,
                'Indian': 4,
                'Alaskan Native': 4,
                'Indian, Alaskan Native':4,
                'indian, alaskan native':4,
                'O': 6,
                'd':6,
                'o':6,
                'Ot': 6,
                'Other': 6,
                'Portuguese': 6,
                'portuguese':6,
                'X': 6, #put X as other
                'x':6,
                'Z': 9,
                's':9,
                'z':9,
                'U': 9,
                'g':9,
                'u':9,
                'Un': 9,
                'Unknown': 9,
                'unknown':9,
                'Not Specified': 9,
                'Nomap': 9,
                'other':6,
                'Other POC':6,
                'not provided':9,
                ' ':9,
                'currently unavailable':9,
                'Unknown Race':9
            }

        self.eyeColor_mapping = {
                'Black': 1,
                'black':1,
                'black eyes':1,
                'Blk':1,
                'blk':1,
                'Blue':2,
                'blue':2,
                'blue eyes':2,
                'Blu':2,
                'blu':2,
                'Brown':3,
                'brown':3,
                'Bro':3,
                'brn':4,
                'hzl':6,
                'bro':3,
                'brown eyes':3,
                'aub':3,
                'mar': 3, #assuming Mar = maroon = brown/red-ish
                'maroon':3,
                'Gray':4,
                'Gry':4,
                'gry':4,
                'gray':4,
                'grey':4,
                'gray eyes':4,
                'Green':5,
                'green eyes':5,
                'green':5,
                'Grn':5,
                'grn':5,
                'Hazel':6,
                'hazel eyes':6,
                'hazel':6,
                'Haz':6,
                'haz':6,
                'Unknown': 9,
                'unknown':9,
                'xxx':9,
                'Zz':9,
                'unk': 9,
                'bln':9,
                'brz':9,
                'dbr':9,
                'lbr':9,
                'dgr':9,
                'mx':9,
                'zz':9,
                'multicolor':9,
                'Currently Unavailable':9,
                'blond':9,
                'currently unavailable':9,
                'classification':9
            }

        self.hairColor_mapping = { 
                'Bald':1,
                'bald (fully)': 1,
                'bald hair':1,
                'unknown or completely bald':1,
                'unkown/bald':1,
                'bald':1,
                'Bld':1,
                'bal':1,
                'Shv':1,
                'Slp':1,
                'Unkown/bald':1,
                'Black':2,
                'black':2,
                'Blk':2,
                'blk':2,
                'bkl':2,
                'black hair':2,
                'Blond':3,
                'blonde hair':3,
                'Bln':3,
                'bln':3,
                'bld':3,
                'Blonde':3,
                'blonde':3,
                'blond':3,
                'Brown':4,
                'tan':4,
                'brn':4,
                'hzl':4,
                'haz':4,
                'brown':4,
                'brown hair':4,
                'hazel':4,
                'Bro':4,
                'bro':4,
                'Red':5,
                'red hair':5,
                'auburn':5,
                'aub':5,
                'red':5,
                'Auburn':5,
                'Red/auburn':5,
                'red or auburn':5,
                'red/auburn':5,
                'Aub':5,
                'White':6,
                'Gray':6,
                'grey or partly grey':6,
                'gray':6,
                'Grey':6,
                'grey':6,
                'Whi':6,
                'whi':6,
                'white':6,
                'wht':6,
                'san':6,
                'Gry':6,
                'gray hair':6,
                'gry':6,
                'sandy':6,
                'sdy':6,
                'Other':7,
                'oth':7,
                'Oli':7,
                'oli':7,
                'Green':7,
                'green':7,
                'Grn':7,
                'orange':7,
                'pink':7,
                'slp':7,
                'shv':7,
                'pnk':7,
                'blue':7,
                'purple':7,
                'blu':7,
                'bur':9,
                'ong':7,
                'grn':7,
                'ple':7,
                'med':9,
                'lbr':9,
                'brz':9,
                'dbr':9,
                'dgr':9,
                'sil':9,
                'Unknown':9,
                'unk':9,
                'unknown hair':9,
                'dyed unusual color':9,
                'xxx':9,
                'Currently Unavailable':9,
                'other':7,
                ' ':9,
                'unknown':9,
                'currently unavailable':9,
                'eyes': 9
            }
        self.county_facilities = {
                'Amador' : 'Amador Co. Jail',
                'Calaveras' : 'Calaveras Co. Jail',
                'Fresno' : 'Fresno County Jail', 
                'Humboldt' : 'Humboldt County Correctional Facility',
                'Inyo' : 'Inyo Co. Jail',
                'Kern' : 'Unknown',
                'Kings' : 'Unknown',
                'Lake' : 'Lake Co. Hill Rd. Corr. Fac.',
                'Madera' : ' Madera Co. Jail',
                'Marin' : 'Marin Co. Jail',
                'Mendocino' : 'Mendocino Co. Jail',
                'Mono' : 'Mono Co. Jail',
                'Napa' : 'Napa Co. Jail',
                'Nevada' : 'Nevada Co. - Wayne Brown Corr. Fac.',
                'San_Luis_Obispo' : 'San Luis Obispo Co. Jail',
                'Santa_Cruz' : 'Unknown',
                'Shasta' : 'Shasta Co. Jail',
                'Sutter' : 'Sutter Co. Jail',
                'Tehama' : ' Tehama Co. Jail', 
                'Yuba' : 'Yuba Co. Jail',
                'Pv' : 'Placerville Jail',
                'Lt' : 'El Dorado Co. Jail - South Lake Tahoe Jail',
                'Sp' : 'South Placer Jail',
                'Pc' : ' Placer Co. Jail'
            }
        self.El_Dorado_Housing = {
                'pv' : 'Placerville Jail',
                'lt' : 'El Dorado Co. Jail - South Lake Tahoe Jail'
            }
        self.Placer_Housing = {
                'sp' : 'South Placer Jail',
                'pc' : 'Placer Co. Jail',
                'unknown': 'Unknown',
                'th': ' Placer Co. Jail',
            }
        self.topcharge_mapping = {
            'Property':1,
            'Violent':2,
            'Public Order':3,
            'Drug':4,
            'Dui Offense':5,
            'DUI Offense':5,
            'Criminal Traffic':6,
            'Criminal traffic':6,
            'Tbd':9,
            'TBD':9,
            'Unknown':9
        }
    
    
    def rename_columns(self):
        self.data.rename(columns=self.column_mapping, inplace=True)
        # Check if the columns exist in the data before selecting them
        columns_to_select = [col for col in self.columns_to_keep if col in self.data.columns]
        #Reindex the data to include all columns and set missing values to NaN
        self.data = self.data[columns_to_select].reindex(columns=self.columns_to_keep)

    def map_gender(self):
        self.data['sex'].fillna('Unknown', inplace = True)
        self.data.loc[:,'sex'] = self.data['sex'].map(self.gender_mapping).fillna(self.data['sex'])

    def map_race(self):
        self.data['race'].fillna('Unknown', inplace = True)
        self.data.loc[:,'race'] = self.data['race'].map(self.race_mapping).fillna(self.data['race'])

    def map_eye_color(self):
        self.data['eyeColor'].fillna('Unknown', inplace = True)
        self.data.loc[:,'eyeColor'] = self.data['eyeColor'].map(self.eyeColor_mapping).fillna(self.data['eyeColor'])

    def map_hair_color(self):
        self.data['hairColor'].fillna('Unknown', inplace = True)
        self.data.loc[:,'hairColor'] = self.data['hairColor'].map(self.hairColor_mapping).fillna(self.data['hairColor'])

    def map_housing1(self):
        #self.data['housing1'] = self.data['county']
        self.data['housing1'].fillna('Unknown', inplace = True)
        self.data.loc[:,'housing1'] = self.data['housing1'].map(self.Placer_Housing).fillna(self.data['housing1'])

    def map_topcharge(self):
        self.data.loc[:,'topcharge'].fillna('Unknown', inplace = True)
        self.data.loc[:,'topcharge'] = self.data['topcharge'].map(self.topcharge_mapping).fillna(self.data['topcharge'])
        
    def display_data(self):
        self.data['height'].fillna(70, inplace = True)
        self.data['weight'].fillna(183.5, inplace = True)
        self.data['age'].fillna(self.data['age'].mean(), inplace = True)
        #self.data.fillna('Unknown', inplace = True)
        print("Unique values in all column after mapping:")
        print("Sex: ", self.data['sex'].unique())
        print("Race: ",self.data['race'].unique())
        print("Eye Color: ",self.data['eyeColor'].unique())
        print("Hair Color: ",self.data['hairColor'].unique())
        print("Housing1: ",self.data['housing1'].unique())
        print("Top Charge: ", self.data['topcharge'].unique())
        display(self.data)
            
    def convert_height(self):
        
        def height_to_inches(height_str):
            try:
                feet, inches = height_str.split("\'")
                feet = int(feet.strip())
                #inches = int(inches.replace('\' ', '').strip())
                #inches = int(inches.strip().rstrip("in(s)")) #remove spaces and trailing
                inches = int(inches.strip().rstrip("\"")) #remove spaces and trailing
                #feet = int(height_str // 100)
                #inches = int(height_str % 100)
                return (feet * 12) + inches
            except:
                return None

        self.data.loc[:,'height'] = self.data['height'].apply(height_to_inches)
        #self.data['height'] = self.data['height'].str.replace(' inches', '', regex=False)
        #self.data['height'] = pd.to_numeric(self.data['height'], errors='coerce')

        

    def clean_weight(self):
        self.data.loc[:,'weight'] = self.data['weight'].replace('Unknown', 183.5)
        self.data.loc[:,'weight'] = self.data['weight'].astype(str)
        self.data.loc[:,'weight'] = self.data['weight'].str.replace(r'Lbs\.?', '', case=False, regex=True).str.strip()
        self.data.loc[:,'weight'] = pd.to_numeric(self.data['weight'], errors='coerce')
        

    def clean_bail_and_bond(self):
        self.data.loc[:,'bail'] = self.data['bail'].astype(str)
        self.data.loc[:,'bail'] = self.data['bail'].str.replace('$', '', regex=False).str.replace(',', '', regex=False)
        self.data.loc[:,'bail'] = pd.to_numeric(self.data['bail'], errors='coerce')


        self.data.loc[:,'bond'] = self.data['bond'].astype(str)
        self.data.loc[:,'bond'] = self.data['bond'].str.replace('$', '', regex=False).str.replace(',', '', regex=False)
        self.data.loc[:,'bond'] = pd.to_numeric(self.data['bond'], errors='coerce')

    def convert_dates(self):
        #self.data.loc[:,'bookingDate'] = self.data['bookingDate'].str.replace('ut', 'Unknown')
        #self.data.loc[:,'bookingDate'] = self.data['bookingDate'].str.replace('scw', 'Unknown')
        #self.data.loc[:,'bookingDate'] = self.data['bookingDate'].str.replace('rc', 'Unknown')
        #self.data.loc[:,'bookingDate'] = self.data['bookingDate'].str.replace('pending', 'Unknown')
        #self.data.loc[:,'bookingDate'] = self.data['bookingDate'].str.split(' ').str[0]
        #self.data.loc[:,'firstappearance'] = self.data['firstappearance'].str.split(' ').str[0]
        #self.data.loc[:,'date'] = self.data['date'].str.split(' ').str[0]
        date_columns = ['bookingDate', 'dob', 'firstappearance', 'date']
        for col in date_columns:
            # Replace 'Unknown' with NaT (Not-a-Time)
            self.data.loc[:,col] = self.data[col].replace('Unknown', pd.NaT)
            self.data.loc[:,col] = pd.to_datetime(self.data[col]).dt.strftime('%Y-%m-%d')
    
    def calculate_age(self):        
        # If dob is available, calculate age base on dob
        #if 'dob' in self.data.columns:
            self.data['date'] = pd.to_datetime(self.data['date'])
            self.data['dob'] = pd.to_datetime(self.data['dob'])
            self.data['age'] = self.data['date'].dt.year - self.data['dob'].dt.year
            
            # Calculate average age (excluding 'Unknown' values)
            #avg_age = self.data['age'][self.data['age'].isna()].astype(float).mean()

            # Replace remaining 'Unknown' values with the average age
            self.data['age'].fillna(self.data['age'].mean(), inplace = True)
        
        # If dob not available
        #elif 'dob' not in self.data.columns:
            #unknown_age_mask = self.data['age'] == 'unknown'
            #Calculate average age
            #avg_age = self.data['age'][se.fdata['age'] != 'Unknown'].astype(int).mean()
            #Fill unknown value with average age
            #self.data.loc[unknown_age_mask,'age'] = avg_age
            
        #self.data['dob'] = pd.to_datetime(self.data['dob']).dt.strftime('%Y-%m-%d')
    
    def calculate_incarcerated_days(self):
    # Ensure 'firstappearance' and 'date' columns are in datetime format
        self.data['firstappearance'] = pd.to_datetime(self.data['firstappearance'])
        self.data['date'] = pd.to_datetime(self.data['date'])
            
        # Group by 'nameFull' and 'firstappearance' and select rows with the maximum 'date'
        #grouped_data = self.data.groupby(['nameFull', 'firstappearance'])['date'].idxmax()

        # Use the filtered index to get the desired rows
        #grouped_data = self.data.loc[grouped_data]

        # Calculate incarcerated days and store it in a new column
        self.data['incarcerated_days'] = (self.data['date'] - self.data['firstappearance']).dt.days
        
    def process_data(self):
        self.rename_columns()
        self.map_gender()
        self.map_race()
        self.map_eye_color()
        self.map_hair_color()
        #self.map_housing1()
        self.map_topcharge()
        self.convert_height()
        self.clean_weight()
        self.clean_bail_and_bond()
        self.convert_dates()
        #self.calculate_age()
        self.calculate_incarcerated_days()
        self.display_data()

Note: 
- Calculate_age when there's no Age column
- Use meta.facility_name for county without Housing Location/Housing 1
- Average Height: In the United States, the average height for adult men is approximately 5 feet 9 inches (69 inches or 175.3 cm), and for adult women, it's around 5 feet 4 inches (64 inches or 162.6 cm). Fill unknown with 66.5
- Average Weight: The average weight for adults in the United States can vary significantly. On average, adult men weigh around 197 pounds (89.4 kg), and adult women weigh around 170 pounds (77.1 kg). fill unknown with 183.5

In [343]:
import pandas as pd

df = pd.read_csv('CA/Placer.csv')
display(df)

/var/folders/vg/77c2fjdd1ll302qk0ng5rc6w0000gn/T/ipykernel_48537/3303762633.py:3: DtypeWarning: Columns (17,18,19,20,21,22,23,24,25,26,27,28,57,58,59,60,61,62,63,64,65,66,67,68,79,80,81,82,83,84,85,86,87,88,89,90,101,102,103,104,105,106,107,108,109,110,111,112,123,124,125,126,127,128,129,130,131,132,133,134,145,146,147,148,149,150,151,152,153,154,155,156,167,168,169,170,171,172,173,174,175,176,177,178,214,215,216,217,218,219,220,221,222,223,224,225,250,258,259,260,261,262,263,271,272,273,274,275,276,283) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('CA/Placer.csv')

,_id,Age,Age_Standardized,Arresting_Agency,Booking_Date,Booking_Status,Booking_Time,Charges[0].Bail_Str,Charges[1].Bail_Str,Charges[2].Bail_Str,...,meta.until_next_booking,Scheduled_Release_Date,meta.since_last_booking,Inmate_ID,Bond_Standardized.flags[0],Bond_Standardized.flags[1],Bond_Standardized.flags[2],Classification_Text_Standardized[0].field,Classification_Text_Standardized[0].value,Classification_Text_Standardized[0].standard
0,60e9492531de019b062cb95e,40.0,40.0,other,2021-05-28,booking process completed and bail may be post...,18:13,No Bail,No Bail,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,60f04c01dcaaee6e105a4986,19.0,19.0,roseville police department,2021-07-14,booking process pending,16:57,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,628a3744a2bacd38f997bf5c,19.0,19.0,california parks & recreation,2022-05-21,booking process completed and bail may be post...,17:37,"$5,000.00",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,614472e9d9f7a79e21820b11,29.0,29.0,placer county sheriff's office,2021-09-16,booking process completed and bail may be post...,22:22,No Bail,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,61583a8dac12cd440e4f058a,51.0,51.0,lincoln police department,2021-10-01,booking process pending,22:55,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15832,6304261054980fce041394d9,56.0,56.0,roseville police department,2022-07-28,booking process completed and bail may be post...,12:20,No Bail,No Bail,No Bail,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15833,6246f79f473f7cec25e4bc7a,39.0,39.0,placer county sheriff's office,2022-03-31,booking process completed and bail may be post...,13:38,"$25,000.00",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15834,624c3da40045d911b4c402e5,68.0,68.0,other,2022-04-04,booking process completed and bail may be post...,12:27,No Bail,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15835,61e17797aa4cf37fdd124e8e,42.0,42.0,roseville police department,2022-01-13,booking process completed and bail may be post...,18:34,"$10,000.00",NaN,NaN,...,37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15836,6229fdc28aa36e0e5e5e1266,43.0,43.0,roseville police department,2022-03-09,booking process completed and bail may be post...,17:30,No Bail,No Bail,NaN,...,NaN,2023-02-06,37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [320]:
import pandas as pd

# Assuming self.data is your DataFrame

# Convert 'bookingDate' to datetime with 'coerce' option
df['Booking_Date'] = pd.to_datetime(df['Booking_Date'], format='%Y-%m-%d', errors='coerce')

# Convert 'DOB' to datetime with 'coerce' option
df['DOB'] = pd.to_datetime(df['DOB'], format='%Y-%m-%d', errors='coerce')

In [309]:
import pandas as pd

# Assuming you have a DataFrame 'df' and the list of date columns
date_columns = ['DOB', 'meta.first_seen', 'meta.last_seen']

# Iterate through the date columns and check for the presence of 'm'
columns_with_m = [col for col in date_columns if df[col].str.contains('02/53/1983').any()]

print("Columns with 'm' in their values:", columns_with_m)

KeyError: 'DOB'

In [95]:
import pandas as pd

# Assuming df is your DataFrame
df = df.applymap(lambda x: str(x).replace('\xa0', '') if pd.notnull(x) else x)

In [344]:
data = pd.DataFrame(df)
data_mapper = DataCleaning(data)
data_mapper.process_data()

df = data_mapper.data

Unique values in all column after mapping:
Sex:  [1 0 9]
Race:  [9]
Eye Color:  [9]
Hair Color:  [9]
Housing1:  ['Placer Co. Jail']
Top Charge:  [2 9 3 6 1 4 5]

,nameFull,bookingNumber,bookingDate,caseNumber,inmateNumber,housing1,housing1a,housing2,housing3,nameLast,...,hairColor,height,weight,bond,bail,topcharge,firstappearance,county,date,incarcerated_days
0,A FOU SAELEE,NaN,2021-05-28,NaN,NaN,Placer Co. Jail,NaN,NaN,a,NaN,...,9,70,183.5,NaN,NaN,2,2021-05-29,Placer,2021-09-03,97
1,AALIYAH DIVINE LEE,NaN,2021-07-14,NaN,NaN,Placer Co. Jail,NaN,NaN,bkg,NaN,...,9,70,183.5,25000.0,25000.0,9,2021-07-15,Placer,2021-07-15,0
2,AALIYAH ISIDRA ALVAREZ,NaN,2022-05-21,NaN,NaN,Placer Co. Jail,NaN,NaN,bkg,NaN,...,9,70,183.5,5000.0,5000.0,3,2022-05-22,Placer,2022-05-22,0
3,AARON ANDREW EMERSON,NaN,2021-09-16,NaN,NaN,Placer Co. Jail,NaN,NaN,i,NaN,...,9,70,183.5,NaN,NaN,3,2021-09-17,Placer,2021-11-19,63
4,AARON CALLEE HAMMOCK,NaN,2021-10-01,NaN,NaN,Placer Co. Jail,NaN,NaN,bkg,NaN,...,9,70,183.5,2500.0,2500.0,9,2021-10-02,Placer,2021-10-02,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15832,ZOUHIR ABOULATHAR,NaN,2022-07-28,NaN,NaN,Placer Co. Jail,NaN,NaN,inf,NaN,...,9,70,183.5,NaN,NaN,1,2022-08-22,Placer,2023-07-06,318
15833,ZSOLT BENEDEK,NaN,2022-03-31,NaN,NaN,Placer Co. Jail,NaN,NaN,g,NaN,...,9,70,183.5,25000.0,25000.0,9,2022-04-01,Placer,2022-04-04,3
15834,ZU CHENG XIAO,NaN,2022-04-04,NaN,NaN,Placer Co. Jail,NaN,NaN,inf,NaN,...,9,70,183.5,NaN,NaN,1,2022-04-05,Placer,2022-04-09,4
15835,ZUBIN DIMITRI BOGDANOFF,NaN,2022-01-13,NaN,NaN,Placer Co. Jail,NaN,NaN,inf,NaN,...,9,70,183.5,10000.0,10000.0,3,2022-01-14,Placer,2022-02-01,18
15836,ZUBIN DIMITRI BOGDANOFF,NaN,2022-03-09,NaN,NaN,Placer Co. Jail,NaN,NaN,e,NaN,...,9,70,183.5,NaN,NaN,1,2022-03-10,Placer,2022-11-17,252

In [345]:
display(df['age'])

0        40.0
1        19.0
2        19.0
3        29.0
4        51.0
         ...
15832    56.0
15833    39.0
15834    68.0
15835    42.0
15836    43.0
Name: age, Length: 15837, dtype: float64

In [346]:
import pandas as pd

# Assuming df is your DataFrame
#df['county'] = df['county'].str.replace('_', ' ')


# Now, underscores in the 'County' column have been replaced with spaces

for column in df.columns:
    unique_values = df[column].unique()
    print(f"Unique values in {column}: {unique_values}")

Unique values in nameFull: ['A FOU SAELEE' 'AALIYAH DIVINE LEE' 'AALIYAH ISIDRA ALVAREZ' ...
 'ZSOLT BENEDEK' 'ZU CHENG XIAO' 'ZUBIN DIMITRI BOGDANOFF']
Unique values in bookingNumber: [nan]
Unique values in bookingDate: ['2021-05-28' '2021-07-14' '2022-05-21' ... '2017-03-19' '2016-11-17'
 '2020-06-07']
Unique values in caseNumber: [nan]
Unique values in inmateNumber: [nan]
Unique values in housing1: ['Placer Co. Jail']
Unique values in housing1a: [nan]
Unique values in housing2: [nan]
Unique values in housing3: ['a' 'bkg' 'i' 'h' 'ms2' 'inf' 'g' 'o' 'd' 'f' 'r' 'e' 'b' 'ms4' 'l' 'j'
 nan 'ms1' 'p' 'c' 'm' 'nc' 'n' 'k' 'van' 'bnr' 'trp' 'tbk' 'x']
Unique values in nameLast: [nan]
Unique values in nameFirst: [nan]
Unique values in nameMiddle: [nan]
Unique values in age: [40.         19.         29.         51.         35.         41.
 34.         50.         49.         37.         38.         44.
 31.         23.         24.         36.         39.         32.
 25.         43.         56.         47.         42.         30.
 22.         33.         26.         54.         37.73230341 27.
 28.         20.         45.         18.         48.         55.
 21.         46.         62.         52.         53.         65.
 60.         78.         79.         57.         64.         59.
 71.         69.         63.         61.         58.         72.
 68.         66.         80.         73.         67.         76.
 77.         70.         75.         74.         82.         81.
 92.         87.         83.         86.         84.         88.
 90.        ]
Unique values in dob: [nan]
Unique values in sex: [1 0 9]
Unique values in race: [9]
Unique values in eyeColor: [9]
Unique values in hairColor: [9]
Unique values in height: [70]
Unique values in weight: [183.5]
Unique values in bond: [nan 25000.0 5000.0 2500.0 82500.0 25500.0 150000.0 200000.0 100000.0
 60000.0 70000.0 90000.0 50000.0 51500.0 15500.0 10000.0 35000.0 145000.0
 1000.0 50500.0 15000.0 7500.0 30000.0 250000.0 55000.0 110000.0 375000.0
 5500.0 16000.0 2200000.0 185000.0 26650.0 565000.0 50.0 175000.0 80000.0
 300000.0 500000.0 122000.0 27000.0 75000.0 102500.0 45000.0 120000.0
 65000.0 20500.0 35500.0 3500.0 85000.0 1000000.0 1300000.0 28000.0
 40000.0 82000.0 20000.0 170000.0 125000.0 6000.0 325000.0 350000.0 750.0
 26000.0 400000.0 280000.0 130000.0 190000.0 2750.0 25050.0 500.0 136000.0
 15150.0 57500.0 8500.0 10500.0 105000.0 155000.0 50150.0 750000.0 9000.0
 17500.0 22500.0 60500.0 61000.0 1500.0 210000.0 181000.0 415000.0
 167250.0 36500.0 25515.0 11500.0 42500.0 115000.0 160000.0 315000.0
 32500.0 81000.0 140000.0 52500.0 58000.0 12500.0 6500.0 335000.0 108000.0
 152500.0 63500.0 1125000.0 26500.0 127500.0 18500.0 2000.0 27500.0
 116500.0 79500.0 195000.0 225000.0 142500.0 122500.0 220000.0 28500.0
 23500.0 101000.0 3000.0 7200.0 100500.0 100.0 14500.0 13500.0 525000.0
 250.0 151000.0 41000.0 1075000.0 184500.0 255000.0 56000.0 153000.0
 305500.0 116000.0 510000.0 0.0 51000.0 107500.0 95000.0 31000.0 120050.0
 4375000.0 37000.0 15515.0 135000.0 30050.0 126000.0 310550.0 97500.0
 285000.0 16500.0 37500.0 150500.0 100900.0 13000.0 86000.0 110500.0
 272500.0 4500.0 92000.0 77500.0 134500.0 120999.0 1055000.0 7000.0
 390000.0 180000.0 431000.0 275000.0 110050.0 88000.0 2250.0 34000.0
 605500.0 258000.0 11000.0 585500.0 305000.0 53000.0 17000.0 154000.0
 99000.0 121000.0 151500.0 52000.0 47000.0 132500.0 56500.0 215000.0
 395000.0 76000.0 47500.0 326050.0 30665.0 113500.0 30500.0 64000.0
 265000.0 550500.0 4000.0 212500.0 44000.0 165000.0 1050.0 310000.0
 41050.0 295000.0 137000.0 48000.0 14000.0 21150.0 50550.0 245000.0
 31500.0 819000.0 118500.0 35150.0 600000.0 205000.0 21500.0 500500.0
 141000.0 470000.0 230000.0 167500.0 8000.0 21050.0 157500.0 103500.0
 106000.0 40500.0 320000.0 7550.0 57550.0 16550.0 252500.0 70500.0 60350.0
 425000.0 5150.0 68000.0 126500.0 36300.0 180100.0 22000.0 67500.0 71000.0
 550000.0 260000.0 1010000.0 81500.0 5750.0 29500.0 1750.0 65500.0
 230500.0 182500.0 50000.01 31030.0 25408.0 66500.0 61500.0 15900.0
 195500.0 12000.0 237500.0 100050.0 10300.0 18000.0 151885.0 1200.0
 35250.0 561000.0 72500.0 90500.0 214500.0 50100.0 1510000.0 30250.0
 33000.0 60650.0 10750.0 42000.0 7250.0 240000.0 360000.0 156500.0
 321521.0 85515.0 263500.0 405000.0 147500.0 6237.0 24000.0 91000.0 150.0
 46000.0 19500.0 36000.0 775000.0 54500.0 46500.0 440000.0 150050.0
 28015.0 43000.0 21000.0 78500.0 10673.0 350500.0 137500.0 131000.0
 1011000.0 75500.0 505000.0 41500.0 66000.0 107000.0 26450.0 177500.0
 1130000.0 9500.0 235000.0 58015.0 7650.0 430000.0 941500.0 112000.0
 3250.0 63000.0 345000.0 475000.0 10005.0 4850.0 8400.0 51050.0 330000.0
 162500.0 1000035.0 225100.0 40050.0 25505.0 1138500.0 75000.01999999999
 133000.0 10250.0 927500.0 289050.0 200250.0 111500.0 507500.0 10050.0
 59500.0 85500.0 1160000.0 217500.0 156000.0 91500.0 11020.0 35815.0
 79000.0 241500.0 23000.0 465.0 332500.0 191000.0 252620.0 370000.0
 1082500.0 364000.0 39500.0 10000.01 900000.0 2050.0 855000.0 650000.0
 100550.0 105500.0 160500.0 183000.0 157000.0 2650000.0 58375.0 92500.0
 15750.0 201500.0 184000.0 3294.21 290000.0 32150.0 50600.0 367500.0
 200550.0 50200.0 270000.0 57000.0 33030.0 94000.0 55500.0 13750.0
 187500.0 76500.0 153500.0 111000.0 317500.0 450000.0 46545.0 53500.0
 36050.0 112500.0 146000.0 50999.0 95500.0 18700.0 75050.0 203500.0
 535000.0 170500.0 134000.0 48500.0 1.0 2.0 80500.0 120750.0 3550.0
 161000.0 105150.0 2120.0 297500.0 206500.0 22515.0 50750.0 66100.0
 68500.0 255500.0 102000.0 19000.0 425500.0 62500.0 32000.0 50850.0
 520000.0 31300.0 600500.0 77000.0 172500.0 199000.0 410000.0 78000.0
 204000.0 96500.0 33150.0 196500.0 250550.0 242000.0 365000.0 251000.0
 194000.0 29000.0 180150.0 2100000.0 303000.0 1250000.0 355000.0 14030.0
 11030.0 465000.0 20050.0 20200.0 125500.0 214000.0 7515.0 32050.0
 140500.0 127060.0 301500.0 19789.0 33500.0 4845000.0 71500.0 307500.0
 715000.0 25750.0 35665.0 20665.0 20600.0 69500.0 20850.0 650.0 2500000.0
 21600.0 205500.0 45550.0 175250.0 69000.0 312500.0 315500.0 154500.0
 455000.0 45100.0 580000.0 45500.0 6100.0 169000.0 40750.0 59000.0
 560000.0 23918.0 265050.0 50050.0 74000.0 127000.0 87500.0 186000.0
 35000.01 300.0 52600.0 800000.0 675000.0 257500.0 117500.0 62000.0
 13250.0 250500.0 8250.0 6150.0 141500.0 950000.0 530000.0 44500.0
 165500.0 124000.0 380000.0 35050.0 99500.0 65550.0 610000.0 232500.0
 95999.0 550.0 1650.0 44250.0 60050.0 43500.0 7750.0 385000.0 125036.0
 30036.0 7000000.0 700.0 47600.0 1025000.0 123000.0]
Unique values in bail: [nan 25000.0 5000.0 2500.0 82500.0 25500.0 150000.0 200000.0 100000.0
 60000.0 70000.0 90000.0 50000.0 51500.0 15500.0 10000.0 145000.0 50500.0
 15000.0 7500.0 250000.0 110000.0 375000.0 5500.0 1000.0 16000.0 2200000.0
 185000.0 26650.0 30000.0 35000.0 565000.0 50.0 175000.0 80000.0 300000.0
 500000.0 122000.0 27000.0 75000.0 45000.0 120000.0 65000.0 20500.0 3500.0
 85000.0 1000000.0 1300000.0 28000.0 40000.0 82000.0 20000.0 125000.0
 6000.0 325000.0 350000.0 26000.0 280000.0 130000.0 2750.0 25050.0
 136000.0 15150.0 57500.0 8500.0 10500.0 105000.0 500.0 155000.0 50150.0
 9000.0 17500.0 22500.0 60500.0 210000.0 181000.0 415000.0 167250.0
 36500.0 25515.0 11500.0 42500.0 160000.0 315000.0 32500.0 81000.0
 140000.0 52500.0 12500.0 6500.0 115000.0 108000.0 152500.0 55000.0
 63500.0 1125000.0 26500.0 127500.0 18500.0 2000.0 79500.0 195000.0
 225000.0 1500.0 142500.0 122500.0 220000.0 28500.0 23500.0 101000.0
 3000.0 7200.0 100500.0 102500.0 14500.0 13500.0 525000.0 190000.0
 1075000.0 184500.0 255000.0 153000.0 305500.0 116000.0 510000.0 58000.0
 51000.0 107500.0 31000.0 120050.0 4375000.0 37000.0 15515.0 35500.0
 126000.0 97500.0 285000.0 16500.0 37500.0 150500.0 100900.0 272500.0
 92000.0 77500.0 61000.0 134500.0 120999.0 7000.0 390000.0 180000.0
 431000.0 110050.0 88000.0 34000.0 585500.0 305000.0 95000.0 121000.0
 151500.0 135000.0 750000.0 52000.0 11000.0 47000.0 56500.0 215000.0
 395000.0 76000.0 47500.0 326050.0 30665.0 113500.0 64000.0 265000.0
 550500.0 212500.0 17000.0 165000.0 1050.0 310000.0 41050.0 14000.0
 21150.0 245000.0 275000.0 35150.0 205000.0 21500.0 500500.0 470000.0
 230000.0 167500.0 21050.0 157500.0 103500.0 106000.0 40500.0 320000.0
 7550.0 57550.0 170000.0 16550.0 252500.0 60350.0 425000.0 53000.0 27500.0
 5150.0 68000.0 126500.0 180100.0 22000.0 67500.0 71000.0 41000.0 550000.0
 260000.0 1010000.0 81500.0 5750.0 29500.0 1750.0 182500.0 31030.0 25408.0
 250.0 66500.0 61500.0 15900.0 195500.0 30500.0 237500.0 100050.0 13000.0
 10300.0 18000.0 151885.0 35250.0 561000.0 72500.0 90500.0 214500.0
 1510000.0 30250.0 60650.0 10750.0 42000.0 7250.0 240000.0 360000.0
 156500.0 321521.0 85515.0 263500.0 405000.0 132500.0 147500.0 400000.0
 6237.0 24000.0 46000.0 19500.0 56000.0 36000.0 775000.0 54500.0 46500.0
 150050.0 750.0 28015.0 78500.0 10673.0 137500.0 131000.0 75500.0 41500.0
 66000.0 107000.0 26450.0 4500.0 177500.0 9500.0 58015.0 7650.0 430000.0
 941500.0 112000.0 63000.0 475000.0 10005.0 4850.0 235000.0 8400.0 51050.0
 330000.0 162500.0 40050.0 141000.0 25505.0 1138500.0 133000.0 10250.0
 289050.0 200250.0 111500.0 507500.0 10050.0 59500.0 70500.0 217500.0
 295000.0 156000.0 35815.0 79000.0 23000.0 465.0 191000.0 335000.0
 252620.0 1082500.0 364000.0 39500.0 4000.0 3250.0 900000.0 855000.0
 600000.0 100550.0 183000.0 157000.0 2650000.0 58375.0 92500.0 15750.0
 201500.0 290000.0 32150.0 367500.0 105500.0 200550.0 270000.0 12000.0
 57000.0 94000.0 55500.0 13750.0 153500.0 111000.0 317500.0 450000.0
 46545.0 53500.0 91500.0 36050.0 112500.0 146000.0 21000.0 50999.0 18700.0
 203500.0 170500.0 134000.0 48500.0 33000.0 80500.0 120750.0 3550.0
 161000.0 105150.0 2120.0 297500.0 206500.0 22515.0 50750.0 66100.0
 68500.0 255500.0 102000.0 43000.0 19000.0 110500.0 62500.0 50850.0
 31300.0 600500.0 77000.0 172500.0 199000.0 78000.0 96500.0 33150.0
 250550.0 8000.0 365000.0 251000.0 29000.0 1200.0 180150.0 44000.0
 2100000.0 303000.0 355000.0 20050.0 20200.0 214000.0 7515.0 140500.0
 127060.0 32000.0 301500.0 19789.0 33500.0 100.0 307500.0 715000.0 25750.0
 35665.0 20665.0 20600.0 69500.0 2500000.0 21600.0 65500.0 205500.0
 505000.0 45550.0 175250.0 1.0 315500.0 31500.0 580000.0 45500.0 370000.0
 6100.0 169000.0 40750.0 59000.0 86000.0 520000.0 560000.0 23918.0 45100.0
 265050.0 74000.0 127000.0 87500.0 35000.01 52600.0 800000.0 675000.0
 257500.0 117500.0 62000.0 13250.0 250500.0 6150.0 141500.0 950000.0
 530000.0 44500.0 124000.0 380000.0 232500.0 95999.0 1650.0 650000.0
 43500.0 7750.0 76500.0 385000.0 75050.0 47600.0 1025000.0]
Unique values in topcharge: [2 9 3 6 1 4 5]
Unique values in firstappearance: <DatetimeArray>
['2021-05-29 00:00:00', '2021-07-15 00:00:00', '2022-05-22 00:00:00',
 '2021-09-17 00:00:00', '2021-10-02 00:00:00', '2022-12-27 00:00:00',
 '2022-01-21 00:00:00', '2022-09-28 00:00:00', '2020-08-17 00:00:00',
 '2022-09-04 00:00:00',
 ...
 '2021-06-06 00:00:00', '2022-04-25 00:00:00', '2020-08-19 00:00:00',
 '2021-02-07 00:00:00', '2021-01-06 00:00:00', '2021-09-26 00:00:00',
 '2021-03-28 00:00:00', '2021-07-11 00:00:00', '2020-10-24 00:00:00',
 '2021-10-25 00:00:00']
Length: 1036, dtype: datetime64[ns]
Unique values in county: ['Placer']
Unique values in date: <DatetimeArray>
['2021-09-03 00:00:00', '2021-07-15 00:00:00', '2022-05-22 00:00:00',
 '2021-11-19 00:00:00', '2021-10-02 00:00:00', '2023-02-09 00:00:00',
 '2022-02-10 00:00:00', '2022-11-01 00:00:00', '2020-10-05 00:00:00',
 '2022-09-04 00:00:00',
 ...
 '2022-06-12 00:00:00', '2022-12-10 00:00:00', '2021-04-24 00:00:00',
 '2022-09-11 00:00:00', '2023-02-13 00:00:00', '2021-09-12 00:00:00',
 '2021-01-30 00:00:00', '2023-04-16 00:00:00', '2021-12-18 00:00:00',
 '2021-06-12 00:00:00']
Length: 1034, dtype: datetime64[ns]
Unique values in incarcerated_days: [  97    0   63   44   20   34   49    3    2    1   76   39    4   14
  200   32    6   16   85   36   92   12   11    5  181  118  127  154
   72   19  133  177  171  131   37   54  212   22    7   13    9   68
  159  976   23   52   58  297    8   48  402   82  124   28   57   42
  357   24  240   62   18  100  187  156  183   71   75  215   33   15
  166  854  116  472   78   59   70  128  101  134   25   10  214   41
  152   29  162  349  219  193   93  224  262   50   66   45  330  427
   27  174   53 1148   31  211   21  486   80  328  145   89   79  223
  135   17   90  507   88  129  160  108   73   69   35  153  247   40
  123  179  180  413  103   38  170  114  122   64  955  137   77   60
   96   30   61   46   91  234  294   47  102  132   94  146  111   86
   98  236  684  293  147  112  208   81  283   43  188   65  322  126
  270  388  107  344  531   74   26  320  149  105  261  218   55  710
  163  151   87  125  119  281  106  423   51  392  351  117  251  260
  241  917  232  198  167  115  485  207  364  620  617  130  199   83
  113  120  397  168  216   84  252  382  326  458  109  189  587  136
  217  194   67  284  148   56  316   95  104  230  634  165  141  362
  258  321  185  375  244  868  290  158  184  317  201  228  197  405
  611  138  271  309  195  672  209  296  242  409  196  265  310  121
  325  323  469  337  559  339  403  308  605  272  273  225  229  259
  157  169  374  678  144  274  239  192  327  299  110  172  202  421
  139  393  575  206  226  231  243  744  203  369  249  254  205  176
  298  173  356  248  537  361  178  220  288  275  268  319  164  622
  435   99  453  766  253  478  210  571  282  175  140  343  404  267
  314  518  377  698  399  359  387  542  488  515  360  489  651  324
  759  155  394  556  256  346  161  422  429  524  213  757  407  289
  505  479  376  186  783  142  150  352  302  182  379  691  279  338
  245  586  431  640  591  233  285  354  250  295  227  593  487  373
  887  237  385  371  222  603  366  503  204  264  395  669  526  358
  221  414  452  495  648  818  473  255  307  280  448 1137  143  570
  498  266  796  600 1088  463  342  569  291  277  667  834  850  838
  500  558  238  340  246  504  512  365  353  415  400  305  502  492
  468  610  269  336  278  334  191  604  410  613  292  647  484  381
  579  466  633  419  425  300  753  420  386  257  313  341  588  389
  967  286  312  306  482  566  378  355  459  318  440  348  732  363
  480  788  235  345  508  506  590  287  332  304  447  333  773  680
  549  954  263  785  276  513  424  462  418  430  963  464  973  301
  434  941  499  592  629  350  384  315  390  401  437  798  477  625
  190  517  454  396  465 1031  331  372]

In [347]:
df.to_csv('Cleaned Data/Placer.csv', index = False)
print(df.dtypes)

nameFull                     object
bookingNumber               float64
bookingDate                  object
caseNumber                  float64
inmateNumber                float64
housing1                     object
housing1a                   float64
housing2                    float64
housing3                     object
nameLast                    float64
nameFirst                   float64
nameMiddle                  float64
age                         float64
dob                          object
sex                          object
race                         object
eyeColor                     object
hairColor                    object
height                        int64
weight                      float64
bond                         object
bail                         object
topcharge                    object
firstappearance      datetime64[ns]
county                       object
date                 datetime64[ns]
incarcerated_days             int64
dtype: object